#!/bin/sh
set -e

test "$1" = 'configure' || exit 0
update-service --add /etc/sv/dnscache
test -z "$2" || exit 0
chown Gdnslog:adm /var/log/dnscache

# adapt resolv.conf
! grep 'nameserver 127.0.0.1' /etc/resolv.conf >/dev/null || exit 0
test -e /etc/resolv.conf || exec echo 'nameserver 127.0.0.1' >/etc/resolv.conf
sed -e 's/nameserver /# nameserver /g' /etc/resolv.conf >/etc/resolv.conf'{new}'
echo 'nameserver 127.0.0.1' >>/etc/resolv.conf'{new}'
mv -f /etc/resolv.conf'{new}' /etc/resolv.conf
